import os

alpha_flags = "-Wall --std=c++17 -Wno-unused-function -I/usr/include -O2"
alpha_env = Environment(ENV=os.environ, CC="gcc", CCFLAGS=alpha_flags)

sources = ["alphaFactory.cpp"]

Program("alphaFactory", sources)
