(goto-line 1)
(replace-string "$net.net.$varnames" "$egyeb.$varnames" nil)
(goto-line 1)
(replace-string "$net.net.awkc" "$egyeb.awkc" nil)
(goto-line 1)
(replace-string "$net.net.bcc" "$egyeb.bcc" nil)
(goto-line 1)
(replace-string "$net.net.lbounds" "$egyeb.lbounds" nil)
(goto-line 1)
(replace-string "$net.net.measures" "$egyeb.measures" nil)
(goto-line 1)
(replace-string "$net.net.parameters" "$egyeb.parameters" nil)
(goto-line 1)
(replace-string "$net.net.steps" "$egyeb.steps" nil)
(goto-line 1)
(replace-string "$net.net.times" "$egyeb.times" nil)
(goto-line 1)
(replace-string "$net.net.ubounds" "$egyeb.ubounds" nil)
(goto-line 1)
(replace-string "$net.net.variable" "$egyeb.variable" nil)
(goto-line 1)
