#initialize the environment
import os
Import("linkflags")

alg_env = Environment(ENV = os.environ, CC="gcc", CCFLAGS="-O2 -lm", LIBPATHS=["/usr/lib", "/usr/local/lib"], LIBS=["m"], LINKFLAGS=linkflags)
Export('alg_env')
SConscript("./Composition/SConstruct")
SConscript("./Remove/SConstruct")
