/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package editor.domain.measures;

import common.Util;
import editor.domain.NetPage;
import editor.gui.net.IndeterminateListCellRenderer;

/**
 *
 * @author elvio
 */
public class RGMEDD2SolverPanel extends SolverPanel {

    private boolean initializing = true;
    private RGMEDD2SolverParams params = null;
    /**
     * Creates new form RGMEDDSolverPanel
     */
    public RGMEDD2SolverPanel() {
        initComponents();
        Util.reformatPanelsForPlatformLookAndFeel(this);
        initializing = true;
        
        
        comboBox_varOrder.setRenderer(new IndeterminateListCellRenderer());
        for (RGMEDD2SolverParams.VariableOrder vo : RGMEDD2SolverParams.VariableOrder.values())
            comboBox_varOrder.addItem(vo);
        
        initializing = false;
    }

    @Override
    public void initializeFor(SolverParams _params, NetPage page, NetPage evalPage, 
                              boolean simplifiedUI, MeasurePage measPage) 
    {
        initializing = true;
        
        params = (RGMEDD2SolverParams)Util.deepCopy(_params);
        
        checkBox_counterExamples.setSelected(params.genCounterExamples);
        comboBox_varOrder.setSelectedItem(params.varOrder);
        
        // Dependency on the requested formulas
        boolean hasCTL = false;
        for (AbstractMeasure am : measPage.measures) {
            if (am instanceof FormulaMeasure) {
                FormulaMeasure fm = (FormulaMeasure)am;
                switch (fm.getLanguage()) {
                    case CTL:
                        hasCTL = true;
                        break;
                }
            }
        }
        checkBox_counterExamples.setVisible(hasCTL);

        initializing = false;
    }

    @Override
    public void deinitialize() {
        params = null;
    }
    
    @Override
    public SolverParams currParams() {
        return params;
    }

    @Override
    public boolean areParamsCorrect() {
        return true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        comboBox_varOrder = new javax.swing.JComboBox<>();
        checkBox_counterExamples = new javax.swing.JCheckBox();

        jLabel3.setText("Variable order heuristic:");

        comboBox_varOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_varOrderActionPerformed(evt);
            }
        });

        checkBox_counterExamples.setText("Generate counter-examples/witnesses when possible.");
        checkBox_counterExamples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_counterExamplesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox_varOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkBox_counterExamples))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBox_varOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBox_counterExamples)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBox_counterExamplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_counterExamplesActionPerformed
        if (initializing)
            return;
        params.genCounterExamples = checkBox_counterExamples.isSelected();
        fireSolverParamsModified();
    }//GEN-LAST:event_checkBox_counterExamplesActionPerformed

    private void comboBox_varOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_varOrderActionPerformed
        if (initializing)
            return;
        RGMEDD2SolverParams.VariableOrder vo = 
                (RGMEDD2SolverParams.VariableOrder)comboBox_varOrder.getSelectedItem();
        if (vo == params.varOrder)
            return;
        params.varOrder = vo;
        fireSolverParamsModified();
    }//GEN-LAST:event_comboBox_varOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox_counterExamples;
    private javax.swing.JComboBox<RGMEDD2SolverParams.VariableOrder> comboBox_varOrder;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
