
/*
void gdiInvertRect();
void gdiSetRect();
void gdiClearRect();
void gdiDrawingAreaInvertRect();
void gdiDrawingAreaClearRect();
void gdiClearDrawingArea();
void gdiInitDrawingAreaGC();
void gdiResizeDrawingArea();
*/

void UpdateMenuStatusTo();
void SetMouseHelp();
void InitMouseHelp();

int	add_arc_moving() ;
int	add_lisp() ;
int	add_mpar() ;
int	add_mpar_v() ;
int	add_point() ;
int	add_res() ;
int	add_rpar() ;
int	add_rpar_v() ;
int	add_segment() ;
int	add_selected_layer() ;
int	adjust_point() ;
void	afire_trans() ;
int	ask_comm() ;
int	auto_simulation() ;
int	backup_modify() ;
int	backup_not_modify() ;
int	backwrd_enabled() ;
int	backwrd_imm_enabled() ;
struct net_object *create_net() ;
int	calc_point() ;
int	calc_ver() ;
int	calctang() ;
int	cambia_blocco() ;
int	cambia_scala() ;
int	cancel_selected_net() ;
int	change_arc_type() ;
int	change_enabl() ;
int	change_layer_name() ;
int	change_line() ;
int	change_lisp() ;
int	change_md() ;
int	change_point() ;
int	change_res() ;
int	change_tr_knd() ;
int	check_confusion() ;

int	circle() ;
int	cleanup_arc() ;
int	clear_canvas() ;
int	clear_cc() ;
int	clear_deadl() ;
int	clear_ecs() ;
int	clear_implp() ;
int	clear_live() ;
int	clear_me() ;
int	clear_menu() ;
int	clear_message() ;
int	clear_pinv() ;
int	clear_res() ;
int	clear_sc() ;
int	clear_throughputs() ;
int	clear_tinv() ;
int	clear_trap() ;
int	clear_unbound() ;
void	clonate() ;
int	clonate_drop_arcs() ;
int	close_int_sim() ;
int	close_msg_f() ;
int	close_to_vector() ;
int	collect_all() ;
int	collect_ccsets() ;
int	collect_deadl() ;
int	collect_ecsets() ;
int	collect_implp() ;
int	collect_mesets() ;
int	collect_pinvar() ;
int	collect_res() ;
int	collect_scsets() ;
int	collect_tinvar() ;
int	collect_trap() ;
int	collect_unbound() ;
int	color_tracking() ;
int	compute_enabled() ;
int	cont_dragging() ;
int	conv_num() ;
int	copy_place_model() ;
struct net_object *create_net() ;
void	decr_token() ;
int	dehighlight_all() ;
int	dehighlight_cc() ;
int	dehighlight_deadl() ;
int	dehighlight_ecs() ;
int	dehighlight_implp() ;
int	dehighlight_list() ;
int	dehighlight_me() ;
int	dehighlight_pinv() ;
int	dehighlight_sc() ;
int	dehighlight_search() ;
int	dehighlight_tinv() ;
int	dehighlight_trans() ;
int	dehighlight_trap() ;
int	dehighlight_unbound() ;
int	del_point() ;
int	delete_arc() ;
int	delete_layers() ;
int	delete_lisp() ;
int	delete_mpar() ;
int	delete_place() ;
int	delete_result() ;
int	delete_rpar() ;
int	delete_s_a() ;
int	delete_sel_params() ;
int	delete_selected() ;
int	delete_trans() ;
int	delete_unsel_arcs() ;
void	destroy_menu_proc() ;
int	disegno_x() ;
int	disegno_y() ;
int	display_cc() ;
int	display_curtime() ;
int	display_deadl() ;
int	display_ecs() ;
int	display_grid() ;
int	display_implp() ;
int	display_me() ;
int	display_pinv() ;
int	display_sc() ;
int	display_selected_net() ;
int	display_tinv() ;
int	display_trap() ;
int	display_unbound() ;
int	do_fire() ;
int	dot() ;
void	drag() ;
int	draw_arc() ;
int	draw_arrow() ;
int	draw_circle() ;
int	draw_curv() ;
int	draw_marking() ;
int	draw_net() ;
int	draw_net_marking() ;
int	draw_not_hd() ;
int	draw_place() ;
int	draw_seg() ;
int	draw_spline() ;
int	draw_t_row() ;
int	draw_tokens() ;
int	draw_trans() ;
int	draw_vector() ;
void	drop() ;
int	drop_color() ;
int	drop_selected() ;
int	drop_t_rate() ;
int	drop_tag() ;
int	edit_color() ;
int	edit_lisp() ;
int	edit_marking() ;
int	edit_md() ;
int	edit_mpar() ;
int	edit_rate() ;
int	edit_res() ;
int	edit_tag() ;
int	elastic_box() ;
int	elastic_line() ;
char    *emalloc() ;
void	end_boxtracking(int, int) ;
int	end_conf() ;
int	erase_live() ;
int	erase_net_marking() ;
char	*erealloc() ;
int	f_norm_trans() ;
int	fire_close_proc() ;
int	fire_close_proc_alt() ;
void	fire_trans() ;
int	force_simulation() ;
int	free_bkup_netobj() ;
int	free_netobj() ;
int	get_answer_proc() ;
int	get_arc_mult() ;
struct arc_token *get_arc_struct() ;
int	get_arc_type() ;
int	get_comm() ;
struct coordinate *get_coo_struct() ;
char    *getenv() ;
int	get_group() ;
int	get_layer_name() ;
int	get_lisp_kind() ;
int	get_new_color() ;
int	get_new_kind() ;
int	get_new_layer() ;
int	get_new_load() ;
int	get_new_mark() ;
int	get_new_rate() ;
int	get_new_tag() ;
int	get_number_step() ;
int	get_pascal_real() ;
int	get_throughputs() ;
int	get_token_distr() ;
int	get_totime() ;
int	getarcs() ;
int	getname() ;
int	gradua_y() ;
int	help() ;
int	help_co_a_proc() ;
int	help_co_b_proc() ;
int	help_co_c_proc() ;
int	help_co_d_proc() ;
int	help_co_e_proc() ;
int	help_co_g_proc() ;
int	help_md_e_proc() ;
int	help_md_g_proc() ;
void	help_popup_menu() ;
int	help_re_e_proc() ;
int	help_re_g_proc() ;
int	highlight_arc() ;
int	highlight_cc() ;
int	highlight_deadl() ;
int	highlight_ecs() ;
int	highlight_entranslist() ;
int	highlight_implp() ;
int	highlight_item() ;
int	highlight_list() ;
int	highlight_me() ;
int	highlight_pinv() ;
int	highlight_place() ;
int	highlight_sc() ;
int	highlight_search() ;
int	highlight_tinv() ;
int	highlight_trans() ;
int	highlight_trap() ;
int	highlight_unbound() ;
int	histogram() ;
int	histogram_list() ;
int	histogram_list_new() ;
int	hor_line_up() ;
int	init_net() ;
void	incr_token() ;
int	ind_prest_list_new() ;
int	ind_prestazione() ;
int	ind_prestazione_list() ;
int	init_animation() ;
int	init_boxtracking() ;
int	init_break() ;
int	init_canvas() ;
int	init_color() ;
int	init_command_menu() ;
int	init_commands() ;
int	init_dirs() ;
int	init_fire() ;
int	init_fire() ;
int	init_getmsg() ;
int	init_grill() ;
int	init_help2_menu() ;
int	init_help_menu() ;
int	init_highlight() ;
int	init_int_sim() ;
int	init_layer() ;
int	init_linetrack() ;
int	init_moveline() ;
int	init_msgreceiving() ;
int	init_net() ;
int	init_overview() ;
int	init_panel() ;
int	init_pflag_menu() ;
int	init_rescale() ;
int	init_search() ;
int	init_simpan() ;
int	init_simulation() ;
int	init_tflag_menu() ;
int	init_zoom() ;
int	init_net() ;
int	name_cmp() ;
int	rot_trans() ;
int	trans_to_n() ;
int	inv_line() ;
int	inv_vector() ;
int	is_in_move() ;
int	l_tracking() ;
int	limit_selected() ;
int	line_tracking() ;
int	line_up() ;
int	load_file() ;
int	load_live() ;
int	memorizza() ;
int	menu_action() ;
int	mirror_drop() ;
int	mirror_drop_arcs() ;
void	mirror_horizontal() ;
void	mirror_vertical() ;
int	modify_evlist() ;
int	modify_selected() ;
int	modify_trans() ;
int	move_color() ;
int	move_place() ;
int	move_t_rate() ;
int	move_tag() ;
int	move_trans() ;
int	msgrec() ;

int HowManyLayers();
Layer NewLayer();
LayerPun NewLayerList();
void SetLayerName();
void ReinitializeLayers();
void MakeLayerVisible();
void SetInitialLayerDimension();
//Boolean IsLayerListVisible();
void ResetVisibleLayers();
//Boolean IsLayerVisible();
void encode_layer();

struct arc_object   *near_arc_obj() ;
struct trans_object *near_imtrans_obj() ;
struct lisp_object  *near_lisp_obj() ;
struct mpar_object  *near_mpar_obj() ;
struct net_object   *near_node_obj() ;
struct net_object   *near_node_obj() ;
struct net_object   *near_obj() ;
struct place_object *near_place_obj() ;
struct res_object   *near_res_obj() ;
struct rpar_object  *near_rpar_obj() ;
struct trans_object *near_titrans_obj() ;
struct place_object *n_to_place() ;
struct trans_object *n_to_trans() ;


int	new_arc() ;
int	new_imtrans() ;
int	new_inhib() ;
int	new_line() ;
int	new_lisp() ;
int	new_mpar() ;
int	new_panel_s() ;
int	new_place() ;

int	new_res() ;
int	new_rpar() ;
int	new_titrans() ;
int	newpoints() ;
int	next_conf() ;

void	null_proc(void) ;
int	one_step_anim() ;
int	one_step_simulation() ;
int	open_break_proc() ;
int	open_msg_f() ;
int	open_s_a() ;
int	open_s_proc() ;
int	open_s_r() ;
int	open_simpan_proc() ;
int	open_usl() ;
void	pflag_popup_menu() ;
int	place_drop() ;
int	place_tracking() ;
int	popdown_modify() ;
int	popup_modify() ;
int	prepare_lp_mark() ;
int	prepare_lp_bounds() ;
int	prepare_place_model() ;
int	print_layer() ;
int	purge_netobj() ;
int	put_file() ;
int	put_msg(int, ...) ;
int	put_trans() ;
int	putarcs() ;
int	putname() ;
int	quit_popup() ;
int	r_norm_trans() ;
int	read_dirs() ;
int	read_file() ;
int	read_file() ;
int	read_us() ;

int	receive_newstate() ;
int	receive_transition() ;
int	recompute_images() ;

int	redisplay_net() ;
int	rem_B_save() ;
int	rem_R_save() ;
int	remove() ;
int	remove_arc() ;
int	remove_histogram() ;
int	remove_ind_prestazione() ;
int	remove_lisp() ;
int	remove_mem_list() ;
int	remove_mpar() ;
int	remove_place() ;
int	remove_result() ;
int	remove_rpar() ;
int	remove_selected() ;
int	remove_trans() ;
int	rescale_net() ;
int	reset_canvas_reader() ;
int	reset_canvas_scroll() ;
int	reset_color() ;
int	reset_entranslist() ;
int	reset_grill() ;

int	reset_mode_proc() ;
int	reset_net_object() ;
int	reset_selected_layer() ;
int	reset_simulation_screen() ;
int	reset_simulator() ;
int	reset_zoom() ;
int	restore_obj() ;
int	result_sim() ;
int	riadjust() ;
int	rmsomething() ;
int	rotate_trans() ;
int	save_file() ;
int	search_proc() ;
int	see_point() ;
void	select_objects() ;
int	set_backup_R_proc() ;
int	set_bw_enabl() ;
int	set_canvas_tracker() ;
int	set_color() ;
int	set_confidence_level_proc() ;
int	set_delete_proc() ;
int	set_enabled() ;
int	set_grill() ;
int	set_immenabled() ;
int	set_int_sim_visibility() ;
int	set_memory_proc() ;
int	set_no_shots() ;
int	set_simulation_clock() ;
int	set_t_fire_name() ;
int	set_type_B_proc() ;
int	set_type_R_proc() ;
int	set_type_proc() ;
int	set_zoom() ;
int	setup_initialstate() ;
int	setup_mark() ;
int	show_cc() ;
int	show_deadl() ;
int	show_ecs() ;
int	show_implp() ;
int	show_lisp() ;
int	show_live() ;
void	show_lp_lamb() ;
void	show_lp_lmmb() ;
void	show_lp_lxb() ;
void	show_lp_uamb() ;
void	show_lp_ueb() ;
void	show_lp_ummb() ;
void	show_lp_uxb() ;
int	show_me() ;
int	show_moving_place() ;
int	show_moving_trans() ;
int	show_mpar() ;
int	show_one_shot() ;
int	show_pinv() ;
int	show_place_color() ;
int	show_place_mark() ;
int	show_place_tag() ;
int	show_rate() ;
int	show_res() ;
int	show_rpar() ;
int	show_sc() ;
int	show_tag() ;
int	show_throughputs() ;
int	show_tinv() ;
int	show_token_distr() ;
int	show_trans_color() ;
int	show_trans_pri() ;
int	show_trans_rate() ;
int	show_trans_tag() ;
int	show_trap() ;
int	show_unbound() ;
int	simpan_start_proc() ;
int	start_simula() ;

int	synchro_s_r() ;
int	t_rate_tracking() ;
int	tag_tracking() ;
void	tflag_popup_menu() ;
int	timed_fire_modify() ;
int	tok_f_proc() ;
int	trans_drop() ;
int	trans_moving() ;
int	trans_tracking() ;
int	transform_coord() ;
int	type_initial() ;
int	type_lisp() ;
int	type_lisp_def() ;
int	type_md_def() ;
int	type_modify() ;
int	type_not_modify() ;
int	type_rate() ;
int	type_res() ;
int	type_res_def() ;
int	untimed_fire_modify() ;
int	update_layer() ;
int	update_mode() ;
int	val_proc() ;
int	vert_line_up() ;
int	w_put_arc() ;
int	w_put_place() ;
int	write_file() ;
int	write_pt() ;
int	xv_vector() ;
int	xv_writebackground() ;
int	zoom_selected_images() ;
void    SetFunction();
