#!/bin/sh
. great_package.sh
############ GreatSPN2.0 ######################
#
# set net=$3/nets/$1
net=$1

if [ ! -f $1.epd ]
then
	${GREATSPN_SCRIPTDIR}/newMT $1 $3
	GSPN2STATUS=$?
	if [ $GSPN2STATUS -ne 0 ]
	then
		exit $GSPN2STATUS
	fi
fi

echo ""
echo "Start Transient solution"
time ${GREATSPN_BINDIR}/ntrs $net $2 -e0.000001 > .gspn_out 2>&1
if [ $? -ne 0 ]
then
	exit 16 
fi
cat .gspn_out
rm -f .gspn_out > /dev/null 2>&1

echo ntrs

/bin/cp $net.epd $net.mpd
if [ $? -ne 0 ]
then
	exit 31 
fi

${GREATSPN_BINDIR}/gst_prep $net
if [ $? -ne 0 ]
then
	exit 13 
fi

${GREATSPN_BINDIR}/gst_stndrd $net > $net.sta
if [ $? -ne 0 ]
then
	exit 14 
fi

${GREATSPN_BINDIR}/throughput $net >> $net.sta
if [ $? -ne 0 ]
then
	exit 15 
fi

exit 0
