#!/bin/sh
. great_package.sh

if [ ! -f $1.epd ]
then
	${GREATSPN_SCRIPTDIR}/newMT $1 
	GSPN2STATUS=$?
	if [ $GSPN2STATUS -ne 0 ]
	then
		exit $GSPN2STATUS
	fi
fi

echo ""
echo "Encoding CTMC on a Dot file"

time ${GREATSPN_BINDIR}/ggsc $1 -D

echo "# Generation PS file: Compact"
echo ""
dot  $1.ctmc -Tps -o $1.ps

exit 0
