#!/bin/sh
. great_package.sh

if [ ! -f $1.epd ]
then
	${GREATSPN_SCRIPTDIR}/newMT $1 
	GSPN2STATUS=$?
	if [ $GSPN2STATUS -ne 0 ]
	then
		exit $GSPN2STATUS
	fi
fi

echo ""
echo "Encoding CTMC on textual file"

time ${GREATSPN_BINDIR}/ggsc $1 -T

echo "# Generation ctmc file: Compact"
echo ""

exit 0
