import os

Import("basepath")

lemonpath = basepath+"/bin/lemon"
Export("lemonpath")

SConscript("./lemon/SConstruct")
SConscript("./alphaFactory/SConstruct")
SConscript("./DSPN-Tool/SConstruct")

#SConscript("./CSLTA-solver/SConstruct") # seems unused, does not compile


