enum {
    FILE_NEW_HANDLE = 0,
    FILE_OPEN_HANDLE,
    FILE_MERGE_HANDLE,
    FILE_SAVE_HANDLE,
    FILE_SAVEAS_HANDLE,
    FILE_REMOVE_RESULTS_HANDLE,
    FILE_REMOVE_ALL_HANDLE,
    FILE_COMMENT_HANDLE,
    FILE_OPTIONS_HANDLE,
    FILE_PRINT_HANDLE,
    FILE_EXIT_HANDLE,


    EDIT_UNDO_HANDLE,
    EDIT_ADD_HANDLE,
    EDIT_CUT_HANDLE,
    EDIT_PASTE_HANDLE,
    EDIT_MOVE_HANDLE,
    EDIT_MODIFY_HANDLE,
    EDIT_LAYERS_HANDLE,


    VIEW_SPLINE_HANDLE,
    VIEW_TAG_HANDLE,
    VIEW_RATE_HANDLE,
    VIEW_LAYERS_HANDLE,
    VIEW_OVERVIEW_HANDLE,
    VIEW_SEARCH_HANDLE,
    VIEW_PRINTAREA_HANDLE ,

    GRID_NONE_HANDLE,
    GRID_5_HANDLE,
    GRID_10_HANDLE,
    GRID_20_HANDLE,
    GRID_30_HANDLE,
    GRID_40_HANDLE,
    GRID_50_HANDLE,

    ZOOM_1_HANDLE,
    ZOOM_3_2_HANDLE,
    ZOOM_2_HANDLE,
    ZOOM_1_2_HANDLE,
    ZOOM_3_4_HANDLE,

    RESCALE_05_HANDLE,
    RESCALE_06_HANDLE,
    RESCALE_07_HANDLE,
    RESCALE_08_HANDLE,
    RESCALE_09_HANDLE,
    RESCALE_10_HANDLE,
    RESCALE_11_HANDLE,
    RESCALE_12_HANDLE,
    RESCALE_13_HANDLE,
    RESCALE_14_HANDLE,
    RESCALE_15_HANDLE,
    RESCALE_16_HANDLE,
    RESCALE_17_HANDLE,
    RESCALE_18_HANDLE,
    RESCALE_19_HANDLE,
    RESCALE_20_HANDLE,

    NET_STRUCT_HANDLE,
    NET_STRUCT_PINV_HANDLE,
    NET_STRUCT_TINV_HANDLE,
    NET_STRUCT_MINDEAD_HANDLE,
    NET_STRUCT_MINTRAP_HANDLE,
    NET_STRUCT_ECS_HANDLE,
    NET_STRUCT_STRUBOU_HANDLE,

    NET_SOLVE_HANDLE,
    NET_SOLVE_TRG_HANDLE,
    NET_SOLVE_EMC_HANDLE,

    NET_SOLVE_GSPN_HANDLE,
    NET_SOLVE_GSPN_STST_HANDLE,
    NET_SOLVE_GSPN_TRAN_HANDLE,
    NET_SIMULATION_HANDLE,

    SWN_SYMBOLIC_HANDLE,
    SWN_ORDINARY_HANDLE,

    HELP_MOUSE_HELP_HANDLE,
    HELP_ABOUT_HANDLE,
    HANDLESNUM
};
enum {
    POPUP_ADD_HANDLE,
    POPUP_CHANGE_HANDLE,
    POPUP_SELECT_HANDLE,
    POPUP_MOVE_HANDLE,
    POPUP_DELETE_HANDLE,
    POPUP_SHOW_HANDLE,
    POPUP_PASTE_HANDLE,
    POPUP_ROTATE_HANDLE,
    POPUP_PRINTAREA_HANDLE,
    POPUP_REDRAW_HANDLE,
    POPUPHANDLESNUM
};






