enum {
    FILE_NEW_MITEM,
    FILE_OPEN_MITEM,
    FILE_MERGE_MITEM,
    FILE_SAVE_MITEM,
    FILE_SAVEAS_MITEM,
    FILE_REMOVE_RESULTS_MITEM,
    FILE_REMOVE_ALL_MITEM,
    FILE_COMMENT_MITEM,
    FILE_OPTIONS_MITEM,
    FILE_PRINT_MITEM,
    FILE_EXIT_MITEM,
};

enum {
    EDIT_UNDO_MITEM	,
    EDIT_ADD_MITEM	,
    EDIT_CUT_MITEM	,
    EDIT_PASTE_MITEM,
    EDIT_MOVE_MITEM,
    EDIT_MODIFY_MITEM,
    EDIT_LAYERS_MITEM,
    EDIT_MODIFY_CLOCKWISE_MITEM,
    EDIT_MODIFY_FLIPX_MITEM,
    EDIT_MODIFY_FLIPY_MITEM,
    EDIT_MIRROR_MITEM,
    EDIT_MODIFY_CLOCKWISE_45_MITEM,
    EDIT_MODIFY_CLOCKWISE_90_MITEM,
    EDIT_MODIFY_CLOCKWISE_135_MITEM,
    EDIT_MODIFY_CLOCKWISE_180_MITEM	,
    EDIT_MODIFY_CLOCKWISE_M135_MITEM,
    EDIT_MODIFY_CLOCKWISE_M90_MITEM,
    EDIT_MODIFY_CLOCKWISE_M45_MITEM
};

enum {
    VIEW_SPLINE_MITEM,
    VIEW_TAG_MITEM,
    VIEW_RATE_MITEM,
    VIEW_OVERVIEW_MITEM,
    VIEW_SEARCH_MITEM,
    VIEW_PRINTAREA_MITEM,
    VIEW_LAYERS_MITEM
};

enum {
    GRID_NONE_MITEM,
    GRID_5_MITEM,
    GRID_10_MITEM,
    GRID_20_MITEM,
    GRID_30_MITEM,
    GRID_40_MITEM,
    GRID_50_MITEM
};

enum {
    ZOOM_1_MITEM,
    ZOOM_3_2_MITEM,
    ZOOM_2_MITEM,
    ZOOM_1_2_MITEM,
    ZOOM_3_4_MITEM
};

enum {
    RESCALE_05_MITEM,
    RESCALE_06_MITEM,
    RESCALE_07_MITEM,
    RESCALE_08_MITEM,
    RESCALE_09_MITEM,
    RESCALE_10_MITEM,
    RESCALE_11_MITEM,
    RESCALE_12_MITEM,
    RESCALE_13_MITEM,
    RESCALE_14_MITEM,
    RESCALE_15_MITEM,
    RESCALE_16_MITEM,
    RESCALE_17_MITEM,
    RESCALE_18_MITEM,
    RESCALE_19_MITEM,
    RESCALE_20_MITEM
};

enum {
    NET_STRUCT_PINV_MITEM,
    NET_STRUCT_TINV_MITEM,
    NET_STRUCT_MINDEAD_MITEM,
    NET_STRUCT_MINTRAP_MITEM,
    NET_STRUCT_ECS_MITEM,
    NET_STRUCT_STRUBOU_MITEM,
    NET_SOLVE_TRG_MITEM,
    NET_SOLVE_EMC_MITEM,
    NET_SOLVE_GSPN_STST_MITEM,
    NET_SOLVE_GSPN_TRAN_MITEM,
    NET_SIMULATION_MITEM,
    /****11/6/10 MDD by Marco***/
    GSPN_MDD
    /****11/6/10 MDD by Marco***/
};

enum {
    SWN_SYM_SIMULATION,
    SWN_SYM_COMPUTERG,
    SWN_SYM_TRANSIENT,
    SWN_ORD_SIMULATION,
    SWN_ORD_COMPUTERG,
    SWN_ORD_TRANSIENT,
    SWN_ORD_UNFOLD,
    /****17/7/08 ESRG by Marco***/
    SWN_ESRG,
    SWN_DSRG,
    /****17/7/08 ESRG by Marco***/
};

enum {
    EGSPN_SIMULATION,
    EGSPN_COMPUTERG,
    EGSPN_TRANSIENT
};

enum {
    HELP_MOUSE_HELP_MITEM,
    HELP_ABOUT_MITEM
};

enum {
    ADD_MITEM,
    CHANGE_MITEM,
    SELECT_MITEM,
    MOVE_MITEM,
    DELETE_MITEM,
    SHOW_MITEM,
    PASTE_MITEM,
    ROTATE_MITEM,
    PRINTAREA_MITEM,
    ENDSHOW_MITEM,
    REDRAW_MITEM
};


enum {
    PINV_MITEM ,
    MINDEAD_MITEM,
    MINTRAPS_MITEM,
    IMPPLACES_MITEM,
    ABSMB_MITEM,
    AVEMB_MITEM,
};

enum {

    TINV_MITEM,
    ECS_MITEM,
    ME_MITEM,
    SC_MITEM,
    CC_MITEM,
    UNBSEQ_MITEM,
    ACTLIVBOUND_MITEM,
    LIVBOUND_MITEM,
    THRBOUND_MITEM,
};



