/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package editor.gui;

import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author elvio
 */
public class HtmlPageReader extends javax.swing.JDialog {
    
    public static HtmlPageReader thePage = null;

    /**
     * Creates new form HtmlPageReader
     */
    public HtmlPageReader(JFrame parent) {
        initComponents();
        HTMLEditorKit kit = new HTMLEditorKit();
        htmlPane.setEditorKit(kit);
        
        String grammarPage;
        try {
            URL url = getClass().getResource("docs/grammar.html");
            Reader reader = new InputStreamReader(url.openStream());
            final char[] buffer = new char[1024];
            final StringBuilder out = new StringBuilder();
            for (;;) {
                int rsz = reader.read(buffer, 0, buffer.length);
                if (rsz < 0)
                    break;
                out.append(buffer, 0, rsz);
            }
            grammarPage = out.toString();
        }
        catch (IOException e) {
            grammarPage = "<html><body><h1>Error: cannot load the page!</h1></body></html>";            
        }
        htmlPane.setText(grammarPage);
        htmlPane.setCaretPosition(0);
//        JScrollBar verticalScrollBar = scrollPane.getVerticalScrollBar();
//        JScrollBar horizontalScrollBar = scrollPane.getHorizontalScrollBar();
//        verticalScrollBar.setValue(verticalScrollBar.getMinimum());
//        horizontalScrollBar.setValue(horizontalScrollBar.getMinimum());
        
        labelTitle.setText("  Grammar of the expressions:");
        
        setSize(780, 600);
        setLocationRelativeTo(parent);
    }
    
    public static void openPage(JFrame parent) {
        if (thePage == null) {
            thePage = new HtmlPageReader(parent);
        }
        thePage.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        htmlPane = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        buttonClose = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        htmlPane.setEditable(false);
        scrollPane.setViewportView(htmlPane);

        jPanel1.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        buttonClose.setText("Close window");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClose, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        labelTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelTitle.setText("Title");
        getContentPane().add(labelTitle, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buttonCloseActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JEditorPane htmlPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
