/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package editor.gui;

import common.Util;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author elvio
 */
public class NewProjectDialog extends javax.swing.JDialog {

    public boolean canceled = true;
    
    public String getProjectName() { return jTextField_projName.getText(); }
    public boolean getStartWithGspn() { return jCheckBoxGspn.isSelected(); }
    public boolean getStartWithDta() { return jCheckBoxDta.isSelected(); }
    public boolean getStartWithMeasures() { return jCheckBoxMeasures.isSelected(); }
    public PetriNetType getStartPNType() { return (PetriNetType)jComboBoxPNType.getSelectedItem(); }
    
    private static final String START_GSPN_KEY = "start_with_gspn";
    private static final String START_DTA_KEY = "start_with_dta2";
    private static final String START_MEASURE_KEY = "start_with_measures";
    private static final String START_PN_TYPE = "start_pn_type";
    
    public enum PetriNetType {
        PT("PT", "Place/Transition Petri net"),
        CPN("CPN", "Colored (Well-Formed) Petri net"),
        GSPN("GSPN", "Generalized Stochastic Petri net"),
        SWN("SWN", "Stochastic Colored (Well-Formed) Petri net"),
        FullPN("PetriNet", "Full Petri net (all extensions)");
            
        String netPrefix, longDesc;
        private PetriNetType(String netPrefix, String longDesc) {
            this.netPrefix = netPrefix;
            this.longDesc = longDesc;
        }
        @Override
        public String toString() { return longDesc; }
    }

    /**
     * Creates new form NewProjectDialog
     */
    public NewProjectDialog(JFrame frame, boolean isModal) {
        super(frame, isModal);
        initComponents();
        
        setLocationRelativeTo(frame);
        getRootPane().setDefaultButton(jButtonOk);
        jTextField_projName.requestFocusInWindow();
        jTextField_projName.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                if (ke.getKeyCode() == KeyEvent.VK_ESCAPE)
                    NewProjectDialog.this.setVisible(false);
            }
        });
        
        jCheckBoxGspn.setSelected(Util.getPreferences().getBoolean(START_GSPN_KEY, true));
        jCheckBoxDta.setSelected(Util.getPreferences().getBoolean(START_DTA_KEY, false));
        jCheckBoxMeasures.setSelected(Util.getPreferences().getBoolean(START_MEASURE_KEY, true));
        
        for (PetriNetType pnt : PetriNetType.values())
            jComboBoxPNType.addItem(pnt);
        try {
            PetriNetType defType = PetriNetType.valueOf(Util.getPreferences()
                    .get(START_PN_TYPE, PetriNetType.PT.name()));
            jComboBoxPNType.setSelectedItem(defType);
        }
        catch (IllegalArgumentException e) { }
        
        jComboBoxPNType.setEnabled(jCheckBoxGspn.isSelected());
        jCheckBoxMeasures.setEnabled(jCheckBoxGspn.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resourceFactory = new editor.gui.ResourceFactory();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_projName = new javax.swing.JTextField();
        jCheckBoxGspn = new javax.swing.JCheckBox();
        jCheckBoxDta = new javax.swing.JCheckBox();
        jCheckBoxMeasures = new javax.swing.JCheckBox();
        jComboBoxPNType = new javax.swing.JComboBox<PetriNetType>();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();

        setTitle("New project");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New project properties"));

        jLabel1.setIcon(resourceFactory.getPnproNew32());

        jLabel2.setText("Insert the name of the new project:");

        jTextField_projName.setText("New project");

        jCheckBoxGspn.setSelected(true);
        jCheckBoxGspn.setText("Start with an empty model of type:");
        jCheckBoxGspn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGspnActionPerformed(evt);
            }
        });

        jCheckBoxDta.setSelected(true);
        jCheckBoxDta.setText("Start with an empty DTA.");

        jCheckBoxMeasures.setSelected(true);
        jCheckBoxMeasures.setText("Start with a measure table.");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jComboBoxPNType, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBoxGspn)
                            .add(jCheckBoxMeasures)
                            .add(jCheckBoxDta)
                            .add(jLabel2)
                            .add(jTextField_projName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 359, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(6, 6, 6)
                        .add(jTextField_projName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel1))
                .add(28, 28, 28)
                .add(jCheckBoxGspn)
                .add(1, 1, 1)
                .add(jComboBoxPNType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBoxDta)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBoxMeasures)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOk);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        jComboBoxPNType.hidePopup();
        canceled = false;
        setVisible(false);
        Util.getPreferences().putBoolean(START_GSPN_KEY, getStartWithGspn());
        Util.getPreferences().putBoolean(START_DTA_KEY, getStartWithDta());
        Util.getPreferences().putBoolean(START_MEASURE_KEY, getStartWithMeasures());
        Util.getPreferences().put(START_PN_TYPE, getStartPNType().name());
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        jComboBoxPNType.hidePopup();
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jCheckBoxGspnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGspnActionPerformed
        jComboBoxPNType.setEnabled(jCheckBoxGspn.isSelected());
        jCheckBoxMeasures.setEnabled(jCheckBoxGspn.isSelected());
    }//GEN-LAST:event_jCheckBoxGspnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JCheckBox jCheckBoxDta;
    private javax.swing.JCheckBox jCheckBoxGspn;
    private javax.swing.JCheckBox jCheckBoxMeasures;
    private javax.swing.JComboBox<PetriNetType> jComboBoxPNType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_projName;
    private editor.gui.ResourceFactory resourceFactory;
    // End of variables declaration//GEN-END:variables
}
